### ISSUE TITLE
RFC: Error type?

### ISSUE THREAD

**Issue by cite-reader** [pindell-matt/fe_bucket#10]
I'm in the middle of refactoring some of the IO code to make it more Rusty, and I've noticed that `Result::expect` tends to get used to catch application errors.

`expect` translates into a panic, and panics aren't intended to be used the same way as exceptions in other languages. They're more like Erlang-esque "crashes", in that they are supposed to quickly bring down everything inside an isolation boundary. In usual Rust, that's a thread; if the application is built with `panic=abort` then the whole process dies a messy death.

Panics are intended for _internal_ errors; things that "can't ever happen", but that we check for anyway because we're human and humans are fallible. They're not for IO errors, which are (by comparison) totally normal.

The usual thing is to define some kind of error module, which has a general shape like:

``` rust
//! Errors for mylib

use std::result;
use std::io;

/// The standard `Result` synonym
#[derive(Debug, Clone, PartialEq, Eq)]
pub type Result<T> = result::Result<T, Error>;

/// Everything that can possibly go wrong
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Error {
    /// Internal IO failure
    Io(io::Error),
    /// Bad Thing #1
    LibProblem1,
    /// Bad Thing #2
    LibProblem2
    // and so on
}

// Pretend there's implementations of `From`, `std::error::Error`, etc. here...
```

And then operations that might fail return `mylib::errors::Result<T>` instead of `T`-but-maybe-panic.

The question I pose is: what belongs in our `Error` enum?

**Comment by selfup** [comment]
As of now I have no idea? Would you like to make headway on it?

**Comment by selfup** [comment]
Making useful errors for internal errors is going to be interesting haha

``` rust
Io(io::Error)
```

Should possibly retry if it is on read. Otherwise if it is on a write sequence, I have no clue?

Never knew you could monkey patch the Error module!

**Comment by cite-reader** [comment]
This isn't a monkeypatch.

What's going on is defining a _completely new_ module, with completely new types, that just happen to have the same names as items in `std` and `core`. The module system and visibility rules—in particular the _shadowing_ rules—ensure the compiler never gets confused.

**Comment by selfup** [comment]
Just took a look at your recent commit.

Starting to understand what is going on. Makes perfect sense!

Thanks!

**Comment by selfup** [comment]
Thanks for the errors module!
