### ISSUE TITLE
Make a basic High Level README

### ISSUE THREAD

**Issue by selfup** [pindell-matt/fe_bucket#16]
This will help people that accidentally stumble upon this repo, prior to us pushing it to https://crates.io when we turn this into a crate, understand that it is a work in progress!

**Comment by cite-reader** [comment]
+1 for prioritizing this; I don't have a strong understanding of high-level goals myself so I'm basically restricted to doing the pinhole optimizer thing.

**Comment by cite-reader** [comment]
Also may I take this opportunity to evangelize for [AsciiDoc](http://asciidoctor.org/)? It kind of looks like Markdown, but [it's better at its job.](http://asciidoctor.org/docs/user-manual/#compared-to-markdown)

**Comment by selfup** [comment]
I'll take a look, but markdown rules GitHub. Let me take a look!

**Comment by selfup** [comment]
I would also take a look at this: https://doc.rust-lang.org/book/comments.html

`cargo doc` is super powerful

**Comment by cite-reader** [comment]
Oh, for _documenting the code_ rustdoc is definitely the correct choice, which locks you into Markdown. That's not true for the README though, especially since [github understands and renders ASCIIDOC.](https://github.com/github/markup#markups)

**Comment by selfup** [comment]
Ohh interesting. I'll have to look more into ASCIIDOC.

I would prefer to write things in Markdown just because it seems to be the standard even in the [Rust](https://github.com/rust-lang/rust) repository itself.
