### ISSUE TITLE
Duplicated functions?

### ISSUE THREAD

**Issue by cite-reader** [pindell-matt/fe_bucket#28]
We have a number of functions which are essentially aliases at slightly different types.

`json_table` is `read_table` with an unused type parameter. `read_json` _is_ `read_table`. `delete_json` is _a reimplementation_ of `drop_table` at a less specific return type, just like `upgrade_table` reimplements `update_table` except it's not exported.

Are these functions supposed to have different semantics at some point?

**Comment by cite-reader** [comment]
`read_json`, ditto, without even a type parameter.

**Comment by selfup** [comment]
You are correct about `json_table` not using a Type. We will remove that type.

@pindell-matt and I are going to clean up some more functions this week-end.

`upgrade_table` does not use the `create_base_data` function like `update_table does`

One builds a `Data<T>` while getting passed a public facing schema struct (`update_table`); kind of like a patch or face lift. The other gets passed a `Data<T>` that is already built (`upgrade_table`); kind of like a new model. 

Those two will have to stay
