### ISSUE TITLE
RFC: Remove nightly Rust dependency

### ISSUE THREAD

**Issue by cite-reader** [pindell-matt/fe_bucket#8]
There are two things we're relying on in the nightly builds:
1. benchmarking
2. custom plugins, for automatically deriving `serde::Serializable`

The first is no great barrier. Since benchmarks are only useful in development, we can hide them behind a [Cargo feature.](http://doc.crates.io/manifest.html#the-features-section)

The second is a bit more work to replace, but I don't consider it difficult work. Merely tedious. Writing our own serialization code is good for us anyway, like eating our vegetables: with direct control over the serialization format, we can more freely play games with optimizing the in-memory format independent of the on-disk format. We could even add version tags to the serialized form that don't ever need to exist at runtime! Amazing.

The request for comment is mostly, "is this something that sounds like it's worth pursuing?"

**Comment by selfup** [comment]
Well, as a beginner rustacean, I would have no idea where to start? It took me a good amount of time to get things working with serde.

Diesel uses nightly since it uses serde. I know Sean Griffin well enough to respect his stance on sticking with nightly

**Comment by cite-reader** [comment]
I did some mechanical transformations [over here](https://github.com/pindell-matt/rust_bucket/tree/stability) to eliminate our dependency on serde's compiler plugin and make it possible to build on stable. That all worked great.

… except for the part where rustc 1.9.0 hits an internal compiler error trying to build it. Which is not so great.

Whatever the problem is, it's already fixed in the beta channel. Hooray!

**Comment by selfup** [comment]
Awesome! So we should be stable next release? That's really good news

**Comment by cite-reader** [comment]
We could be! There ends up being a _lot_ of code involved in manually implementing `Serialize` and `Deserialize` so I think I want to push `Data` into its own module (the root module can `pub use` it to avoid breaking our current API), but what's there passes all tests on nightly and beta.

We still have benchmarks, too, behind a Cargo feature I've creatively called "benchmarks". `rustup run nightly cargo bench --features benchmarks`, or if the current override is already nightly just the suffix of that command starting at `cargo`.

**Comment by selfup** [comment]
Yea the only problem I see with manually implementing Serialize and Deseriailize, is that anyone using our lib will have to do the same in their schema. That is the last thing I want our users to do.

The hole idea is that the schema set up for devs is super easy, and serde kinda just does its job.

I'm cool with it only working on the next version of stable and up though.

Thank you so much for figuring this out!

**Comment by selfup** [comment]
Ok that's cool that we can still bench mark by asking for it!

Yea testing on nightly and pushing for beta is a great idea for now. Next release comes through and we are ready to roll on stable.

So awesome!

**Comment by selfup** [comment]
Am I wrong in thinking that users will have to implement the same Serialize/Deserialize for their schema, or is your implementation taking care of all this?

So I just took a look and it seems that our users will have to do this for all their public facing structs.

**Comment by selfup** [comment]
@cite-reader Is there any other way to make it work on stable? I am not going to force our users to implement Serialize and Deserialize for every single struct they need. I really do appreciate the work you put into this, but that `sc` directory is to not be touched, unless we add more structs to test that we can take in more than one Type.

**Comment by selfup** [comment]
Unless you can avoid forcing our users to implement Serialize and Deserialize on their schema, I will have to close this issue. This breaks core usability as well as the promise of our API.

**Comment by cite-reader** [comment]
What makes you think this magically won't work with derived instances? I'm curious.

`Cargo.toml`:

``` toml
[package]
name = "derived-buckets"
version = "0.1.0"
authors = ["Alex Hill <alexander.d.hill.89@gmail.com>"]

[dependencies]
serde = "0.7"
serde_macros = "0.7"
fe_bucket = { path = "../rust_bucket" }
```

`src/main.rs`:

``` rust
#![feature(custom_derive, plugin)]
#![plugin(serde_macros)]

extern crate fe_bucket;
extern crate serde;

use fe_bucket::create_table;
use serde::{Serialize, Deserialize};

fn main() {
    let ex = Example::new();
    create_table("derived", &ex).expect("This should have written a thing");
}

#[derive(Debug, Serialize, Deserialize)]
struct Example {
    happy: bool
}

impl Example {
    fn new() -> Example {
        Example { happy: true }
    }
}
```

This compiles and runs as expected, leaving `{"table":"derived","next_id":"1","records":{"0":{"happy":true}}}` in the `db/derived` file. And yes, I do have `stability` checked out in my `rust_bucket` repository.

`rustc` does not care about the provenance of a trait implementation. It would be pointless to track, and probably _would_ lead to unintuitive behavior like some `Serialize` implementations being more equal than others. Fortunately the only thing that matters to method resolution is that such a trait implementation is in scope, and everything is delegated correctly.

Arranging things to work on not-Nightly toolchains offres strictly _more_ freedom to our users. If they want to use Nightly and have a plugin derive their serialization format, they can do that. If they wanted to run on stable, though, they _could do that now_ instead of choosing between "using rust buckets" and "being assured a minor compiler release won't break their code."

**Comment by selfup** [comment]
Ok that makes sense. As long as we state that in the README! But I am not forcing people to write 130 + lines of code per struct if I don't have to.

**Comment by selfup** [comment]
@cite-reader 

Ok awesome. The last PR has been merged.

You may now pull master, and merge new master into your branch!

**Comment by selfup** [comment]
I just merged with no issues:

![stable_merge](https://cloud.githubusercontent.com/assets/9837366/16364179/52ba9ec4-3b9e-11e6-9966-a4659337bab3.PNG)

**Comment by selfup** [comment]
However, how are we going to get the tests to pass on Travis?

![00000night_test](https://cloud.githubusercontent.com/assets/9837366/16364208/f2606990-3b9e-11e6-8649-dfc499d41cbc.PNG)

You'll have to make `cargo test` pass, even on nightly

**Comment by cite-reader** [comment]
That got picked up in the merge, it looks like. Squashing it.

**Comment by selfup** [comment]
Ok yea I see the new changes you just made on your fork
