### ISSUE TITLE
Replace wildcard deps with known bounds

### ISSUE THREAD

**Issue by cite-reader** [pindell-matt/fe_bucket#9]
Latest major.minor seems like a good start, if anyone feels like setting up CI infrastructure we can bisect histories to find more liberal bounds. Or not, that's kind of experimental at the best of times.

**Comment by selfup** [comment]
@pindell-matt Will have to setup Travic CI since this is his repository. I will push up a valid `.travis.yml` so that all that needs to be done is to point Travis to this repo once he has a chance to do so.

**Comment by selfup** [comment]
Travis CI is hooked up.

The tests run automatically now!

**Comment by selfup** [comment]
I think we have satisfied this issue. If not, feel free to comment after close

**Comment by cite-reader** [comment]
We still declare our dependencies like `serde = "*"`. This is a declaration that we will work with any version at all, which... well, we probably can't. Especially if Serde gets a semver major version bump in the future.

The intent of this ticket was to replace those with concrete bounds, like `serde = "0.7"`, which declares we'll work with any Serde release in the 0.7, 0.8, ... families, but we can't guarantee that we'll work with 0.6 or 1.0.

**Comment by selfup** [comment]
Reopened so that we can continue to discuss this.

Thanks for clarifying!

**Comment by carols10cents** [comment]
Also [crates.io disallows uploading crates that have dependencies with wildcard versions](http://doc.crates.io/faq.html#can-libraries-use--as-a-version-for-their-dependencies), so this will need to be resolved before publishing :)

**Comment by selfup** [comment]
@carols10cents That is good to know! 

I'll pull the dep versions from the cargo.lock before pushing to crates.io, and then we can update as time goes on to see what works.

Thanks for the heads up.
